In [1]:
%run "..\T11\Metodo da Potencia Regular - Equipe 14(Daniel e Ubiratan).ipynb"

autovalor => 6.6457513110424165
autovetor => [0.80517185 0.51994284 0.28523279]
autovalor => 49.3831459413551
autovetor => [0.69805185 0.57987878 0.34487082 0.22686645 0.07784574]


In [2]:
import numpy as np

# Método da Potência Inversa Comum

In [3]:
def potencia_inversa(A,v0=np.array([]) ,tolerancia = 1e-10,max_iteracoes=10000):
    if v0.size == 0:
        v0 = np.ones(np.shape(A)[0])

    autValN  = 0 #step 3
    vkN = np.copy(v0) #step 4

    for i in range(max_iteracoes):
        autValV = np.copy(autValN) #step 5

        vkV = np.copy(vkN) #step 6

        x1V = np.divide(vkV,(np.sqrt(np.dot(vkV.T , vkV)))) #step 7

        vkN = np.dot(np.linalg.inv(A),x1V) #step 8

        autValN = np.matmul(x1V.T, vkN) #step 9

        if abs(np.divide( np.subtract(autValN , autValV ),autValN)) < tolerancia: #step 9
            break;

    autValF = 1 / autValN #step 11
    xn = np.copy(x1V)#step 12
    return( autValF , xn)

# BenchMarks

In [4]:
A1 = np.array([
    [5, 2, 1],
    [2, 3, 1],
    [1, 1, 2]
],float)

In [5]:
A2 = np.array([
    [-14,  1,  -2],
    [  1,  -1,   1],
    [ -2,  1, -11]
])

In [6]:
A3 = np.array([
    [40, 8,  4,  2, 1],
    [8, 30, 12,  6, 2],
    [4, 12, 20,  1, 2],
    [2,  6,  1, 25, 4],
    [1,  2,  2,  4, 5]
])

# Resultados do Método

In [7]:
lamb, x = potencia_inversa(A1)
print(f' autovalor => {lamb}')
print(f' autovetor => {x}')

 autovalor => 1.3542486889983678
 autovetor => [ 0.13550299 -0.62953847  0.76506225]


In [8]:
lamb, x = potencia_inversa(A2)
print(f' autovalor => {lamb}')
print(f' autovetor => {x}')

 autovalor => -0.8509230914609324
 autovetor => [0.06259585 0.99435785 0.08564004]


In [9]:
lamb, x = potencia_inversa(A3)
print(f' autovalor => {lamb}')
print(f' autovetor => {x}')

 autovalor => 4.014882942408441
 autovetor => [-0.00909562  0.03206584 -0.13178428 -0.18745222  0.9728225 ]


# Método da Potência Inversa com Deslocamento

In [10]:
def potencia_inversa_deslocamento(A,u=0,v0=np.array([]),tolerancia=1e-10):
    I = np.eye(np.shape(A)[0]) #matriz identidade de A

    if v0.size == 0: #iniciando o vetor de chutes com 1 em todas as posicoes
        v0 = np.ones(np.shape(A)[0])
    
    Â =  (np.subtract(A,(u*I)))#step 1
    
    autValV,x = potencia_inversa(Â,v0,tolerancia) #step 2

    autValN = autValV+u #step 3
    xi = x #step 4
    return autValN,xi


# Resultados do Método

In [11]:
(lamb, x) = potencia_inversa_deslocamento(A1)
print(f' autovalor => {lamb}')
print(f' autovetor => {x}')

 autovalor => 1.3542486889983678
 autovetor => [ 0.13550299 -0.62953847  0.76506225]


In [12]:
lamb, x = potencia_inversa_deslocamento(A2)
print(f' autovalor => {lamb}')
print(f' autovetor => {x}')

 autovalor => -0.8509230914609324
 autovetor => [0.06259585 0.99435785 0.08564004]


In [13]:
lamb, x = potencia_inversa_deslocamento(A3)
print(f' autovalor => {lamb}')
print(f' autovetor => {x}')

 autovalor => 4.014882942408441
 autovetor => [-0.00909562  0.03206584 -0.13178428 -0.18745222  0.9728225 ]


# Todos os auto{valores,vetores}

In [14]:
def todo_valores(matriz,erro=10**-2):
    # return [ (autovalor,[autovetor]), ]
    
    valores = []
    vetores = []
    
    n = len(matriz)
    
    max_lamb, x = potencia(matriz)
    max_lamb = abs(int(max_lamb))
    min_lamb, x = potencia_inversa(matriz)
    min_lamb = abs(int(min_lamb))
    step_size = max_lamb*2/100
    
    for i in range(100):
        step = -max_lamb + (step_size * i)
        lamb, x = potencia_inversa_deslocamento(matriz,u=step)
        existe_proximo = False
        
        for j in valores:
            if j-erro < lamb < j+erro:
                existe_proximo = True
        if not existe_proximo:
            valores.append(lamb)
            vetores.append(x)
        if(len(valores) == n):
            break
    
    return [(valores[i], vetores[i]) for i in range(n)]

In [15]:
todo_valores(A1, 10**-6)

[(1.3542486927803061, array([ 0.13546346, -0.62949893,  0.76510179])),
 (2.0000000008812253, array([-0.57734522,  0.5773268 ,  0.57737878])),
 (6.645751311988452, array([0.80516454, 0.51995015, 0.28524008]))]

In [16]:
todo_valores(A2, 10**-6)

[(-15.127761438716043, array([ 0.88667125, -0.09479565,  0.45257915])),
 (-10.021315469445456, array([-0.4581523 , -0.04760397,  0.88759807])),
 (-0.8509230773825243, array([0.06257779, 0.99435598, 0.08567497]))]

In [17]:
todo_valores(A3, 10**-6)

[(4.014882958687259,
  array([-0.00909367,  0.0320379 , -0.13174773, -0.18744489,  0.9728298 ])),
 (11.642426409119444,
  array([ 0.04132662, -0.59192191,  0.77449835,  0.15538165,  0.15469137])),
 (23.648079475384478,
  array([ 0.10328736, -0.24727881, -0.39382372,  0.87053615,  0.12350951])),
 (31.31146526074319,
  array([-0.70728418,  0.50119965,  0.32980391,  0.36252412,  0.09139833])),
 (49.38314594613726,
  array([0.69806851, 0.57986697, 0.34486306, 0.22685789, 0.07784358]))]