In [95]:
import numpy as np
import math

In [96]:
def comprimento(w):
    w = np.array(w)
    norma = sum( [ w.dot(w) ] )
    norma = math.sqrt(norma)
    return norma
    
def multiplica(m1, m2):
    n = len(m1)
    if n != len(m2):
        print("erro dimensão")
        return None
    result = identidade(n)
    for i in range(n):
        for k in range(n):
            somatorio = 0
            for j in range(n):
                somatorio += m1[i][j] * m2[j][k]
            result[i][k] = somatorio
    return result

def print_matriz(matriz, erro=10**-9):
    n = len(matriz)
    for i in range(n):
        for j in range(n):
            numero = float(matriz[i][j])
            if numero<=erro:
                numero = float(0)
            print("{:.3}".format(numero), end=" ")
        print()

def identidade(n):
    identidade = [[0 for j in range(n)] for i in range(n)]
    for i in range(n):
        identidade[i][i] = 1
    return identidade

def Transposta(matriz):
    n = len(matriz)
    return [ [ matriz[i][j] for i in range(n)] for j in range(n)]

A = [
    [40, 8, 4, 2, 1],
    [8, 30, 12, 6, 2],
    [4, 12, 20, 1, 2],
    [2, 6, 1, 25, 4],
    [1, 2, 2, 4, 5]]
teste = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

In [97]:
def matrizHouseholderBaseadaNaCol_iDaMatrizDoPassoAnterior(matriz, i):
    n = len(matriz)
    I = identidade
    w = [aij if index>i else 0 for index,aij in enumerate(matriz[:][i]) ]
    comprimento_w = comprimento(w)
    
    w_ = [0 if index!=i+1 else comprimento_w for index in range(n)]
    
    N = np.array( w ) - np.array( w_ )
    N = N.tolist()
    
    comprimento_N = comprimento(N)
    
    n_matriz_espelo = np.array( N ) / np.array( comprimento_N )
    
    print("\n H vai ser")
    transposta = np.array( [ [i] for i in n_matriz_espelo[:] ] )
    h = np.array(identidade(n)) - (2* ( n_matriz_espelo * transposta ))
    print( h )
    
    return h.tolist()

In [98]:
def metodoDeHouseholder(matriz_a):
    n = len(matriz_a)
    H = identidade(n)
    velho_a = matriz_a
    for i in range(0,n-2):
        h = matrizHouseholderBaseadaNaCol_iDaMatrizDoPassoAnterior(velho_a, i)
        
        h_transposto = Transposta(h)
        novo_a = multiplica( h_transposto, velho_a )
        novo_a = multiplica( novo_a, h )
        
        velho_a = novo_a
        H = multiplica( H, h )
                
    return (velho_a, H)

In [106]:
resultado = metodoDeHouseholder(A)

print()
for i in resultado[1]:
    for j in i:
        if j < 10**-3:
            print( 0 ,end="\t")
        else:
            print( j ,end="\t")
    print()
print()

resultado = np.array( resultado[0] )
for i in resultado:
    for j in i:
        if j < 10**-3:
            print( 0 ,end="\t")
        else:
            print( j ,end="\t")
    print()


 H vai ser
[[ 1.          0.          0.          0.          0.        ]
 [ 0.          0.86772183  0.43386092  0.21693046  0.10846523]
 [ 0.          0.43386092 -0.42302616 -0.71151308 -0.35575654]
 [ 0.          0.21693046 -0.71151308  0.64424346 -0.17787827]
 [ 0.          0.10846523 -0.35575654 -0.17787827  0.91106087]]

 H vai ser
[[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.          0.         -0.89868951 -0.0226937  -0.4379979 ]
 [ 0.          0.         -0.0226937   0.99972876 -0.00523508]
 [ 0.          0.         -0.4379979  -0.00523508  0.89896075]]

 H vai ser
[[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          0.73605061  0.67692651]
 [ 0.          0.          0.          0.67692651 -0.73605061]]

1.0	0	0	0	0	
0	